version: '3'

services:
    mosquitto:
        image: eclipse-mosquitto
        ports:
            - 1883:1883
            - 8883:8883
            - 8083:8083
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./passwd:/mosquitto/config/passwd
            - /etc/letsencrypt/live/mqtt.genevski.com/cert.pem:/mosquitto/config/cert.pem
            - /etc/letsencrypt/live/mqtt.genevski.com/privkey.pem:/mosquitto/config/privkey.pem
            - /etc/letsencrypt/live/mqtt.genevski.com/chain.pem:/mosquitto/config/chain.pem
            - /etc/letsencrypt/live/mqtt.genevski.com/fullchain.pem:/mosquitto/config/fullchain.pem
            - mosquitto-data:/mosquitto/data

volumes:
    mosquitto-data: